# Generated by Django 5.1.2 on 2025-01-15 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='activity_description',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ceo_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='field',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='employee@uottawa.ca', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='EmployeePassword123!', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='EmployeeUsername', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='student@uottawa.ca', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='StudentPassword123!', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='StudentUsername', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company_name',
            field=models.CharField(default='EmployeeCompany', max_length=50),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('ceo_name', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('activity_description', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeeProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Canada', editable=False, max_length=50)),
                ('university', models.CharField(default='University of Ottawa', editable=False, max_length=50)),
                ('level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], max_length=15)),
                ('status', models.CharField(choices=[('currently', 'Currently Enrolled'), ('alumni', 'Alumni')], max_length=20)),
                ('faculty', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
