# Generated by Django 5.1.2 on 2025-02-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_employee_activity_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='faculty',
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.CharField(default='dummyemail@uottawa.ca', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gpa',
            field=models.IntegerField(default=2.5),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='home_address',
            field=models.CharField(default='500 Generic Street, Generic City, Generic Province, Canada', max_length=80),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.IntegerField(default='1234567890'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_card',
            field=models.FileField(blank=True, null=True, upload_to='student_cards/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
