# Generated by Django 5.1.2 on 2025-02-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_studentprofile_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_card',
            field=models.ImageField(blank=True, null=True, upload_to='student_cards/'),
        ),
    ]
