# Generated by Django 5.0.6 on 2025-03-10 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_studentprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='EmployerUsername', max_length=50, unique=True)),
                ('email', models.EmailField(default='employer@uottawa.ca', max_length=254)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='profile_pictures/')),
                ('company_name', models.CharField(default='EmployerCompany', max_length=50)),
                ('ceo_name', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('activity_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='username',
            field=models.CharField(default='StudentUsername', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='student@uottawa.ca', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('employer', 'Employer'), ('student', 'Student')], max_length=15),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employerProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
